version: 1
disable_existing_loggers: false

formatters:
  json:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: data/logs/crawler.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  mtf_crawler:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  requests:
    level: WARNING
    handlers: [console, file]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]
